# Generated by Django 3.0.6 on 2022-05-21 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_shortlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='shortlist',
        ),
    ]
