# Generated by Django 3.0.6 on 2022-05-21 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_delete_shortlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='shortlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.searchs')),
            ],
            options={
                'db_table': 'shortlist',
            },
        ),
    ]
