# Generated by Django 3.0.6 on 2022-05-22 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0006_auto_20220521_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='searchs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pic1', models.ImageField(default='', upload_to='pictures/')),
                ('Pic2', models.ImageField(default='', upload_to='pictures/')),
                ('name', models.CharField(max_length=100)),
                ('Gender', models.CharField(default='', max_length=10)),
                ('Maritial_status', models.CharField(default='', max_length=20)),
                ('age', models.IntegerField()),
                ('religion', models.CharField(default='', max_length=30)),
                ('education', models.CharField(default='', max_length=100)),
                ('occupation', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=50)),
                ('profileby', models.CharField(default='', max_length=50)),
                ('complexion', models.CharField(default='', max_length=30)),
                ('height', models.CharField(default='', max_length=20)),
                ('weight', models.CharField(default='', max_length=20)),
                ('approval', models.CharField(default='non_approval', max_length=20)),
                ('sort', models.CharField(default='no', max_length=20)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'searchs',
            },
        ),
        migrations.CreateModel(
            name='shortlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dd', to='website.searchs')),
            ],
            options={
                'db_table': 'shortlist',
            },
        ),
    ]
