# Generated by Django 3.0.6 on 2022-05-22 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20220521_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchs',
            name='sort',
        ),
    ]
