# Generated by Django 3.0.6 on 2022-05-22 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_searchs_sort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortlist',
            name='shortlist',
        ),
        migrations.DeleteModel(
            name='searchs',
        ),
        migrations.DeleteModel(
            name='shortlist',
        ),
    ]
