# Generated by Django 3.0.6 on 2022-05-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_searchs_shortlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchs',
            name='slist',
            field=models.CharField(default='', max_length=20),
        ),
    ]
