# Generated by Django 3.0.6 on 2022-05-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20220522_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchs',
            name='slist',
            field=models.CharField(default='', max_length=20),
        ),
    ]
