# Generated by Django 4.0 on 2022-05-22 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20220522_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortlist',
            old_name='shortlist',
            new_name='slist',
        ),
    ]
